// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.28.1
// source: streaming_service.proto

package sample_service

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	StreamData_DataStream_FullMethodName = "/StreamData/DataStream"
)

// StreamDataClient is the client API for StreamData service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type StreamDataClient interface {
	DataStream(ctx context.Context, in *StreamRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[StreamResponse], error)
}

type streamDataClient struct {
	cc grpc.ClientConnInterface
}

func NewStreamDataClient(cc grpc.ClientConnInterface) StreamDataClient {
	return &streamDataClient{cc}
}

func (c *streamDataClient) DataStream(ctx context.Context, in *StreamRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[StreamResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &StreamData_ServiceDesc.Streams[0], StreamData_DataStream_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[StreamRequest, StreamResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type StreamData_DataStreamClient = grpc.ServerStreamingClient[StreamResponse]

// StreamDataServer is the server API for StreamData service.
// All implementations should embed UnimplementedStreamDataServer
// for forward compatibility.
type StreamDataServer interface {
	DataStream(*StreamRequest, grpc.ServerStreamingServer[StreamResponse]) error
}

// UnimplementedStreamDataServer should be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedStreamDataServer struct{}

func (UnimplementedStreamDataServer) DataStream(*StreamRequest, grpc.ServerStreamingServer[StreamResponse]) error {
	return status.Errorf(codes.Unimplemented, "method DataStream not implemented")
}
func (UnimplementedStreamDataServer) testEmbeddedByValue() {}

// UnsafeStreamDataServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to StreamDataServer will
// result in compilation errors.
type UnsafeStreamDataServer interface {
	mustEmbedUnimplementedStreamDataServer()
}

func RegisterStreamDataServer(s grpc.ServiceRegistrar, srv StreamDataServer) {
	// If the following call pancis, it indicates UnimplementedStreamDataServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&StreamData_ServiceDesc, srv)
}

func _StreamData_DataStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(StreamRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(StreamDataServer).DataStream(m, &grpc.GenericServerStream[StreamRequest, StreamResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type StreamData_DataStreamServer = grpc.ServerStreamingServer[StreamResponse]

// StreamData_ServiceDesc is the grpc.ServiceDesc for StreamData service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var StreamData_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "StreamData",
	HandlerType: (*StreamDataServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "DataStream",
			Handler:       _StreamData_DataStream_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "streaming_service.proto",
}
